#!/usr/bin/env python3
#
# MIT License
#
# Copyright (c) 2020 Alex Badics
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
import os
import re

from .code_block_printer import CodeBlockPrinter

from .generator_factory import GeneratorFactory
from .type_cache import TypeCache
from .base import GeneratorInitParameters, SchemaError
from ..settings import Settings

DIR_OF_THIS_FILE = os.path.dirname(__file__)

NOTE_FOR_GENERATED_FILES = """
/* This file was generated by JSON Schema to C.
 * Any changes made to it will be lost on regeneration. */
"""


class RootGenerator:
    def __init__(self, schema, settings: Settings):
        self.settings = settings
        if '$id' not in schema:
            raise SchemaError("", "All schemas must have an ID (a field named '$id')")
        self.root_generator = GeneratorFactory.get_generator_for(
            schema,
            GeneratorInitParameters(
                '',
                schema['$id'],
                schema['$id'],
                schema['$id'] + '_t',
                settings,
                GeneratorFactory,
                TypeCache(),
            )
        )
        self.name = schema['$id']

    def generate_root_parser(self, out_file: CodeBlockPrinter):
        out_file.print("// Splint can't see that: The json_string reference isn't held by the function, because parse_state is dropped at the end of the function.")
        out_file.print("/*@-temptrans@*/")
        out_file.print("bool json_parse_{}_with_len(const char *json_string, size_t json_string_len, {})".format(self.name, self.root_generator.c_type.typed_identifier("out", indirection="*")))
        with out_file.code_block():
            out_file.print("int token_num = builtin_parse_json_string(NULL, NULL, 0, json_string, json_string_len);")
            with out_file.if_block("token_num < 0"):
                out_file.print("return true;")
            with out_file.if_block(f"(size_t) token_num > (size_t) ({self.settings.tokens_buf_max_size}) / sizeof(jsmntok_t)"):
                out_file.print("LOG_ERROR(parser.pos, \"Exceeded maximum allowed buffer size for JSMN token buffer\");")
                out_file.print("return true;")
            out_file.print("parse_state_t parse_state_var;")
            out_file.print("parse_state_t *parse_state = &parse_state_var;")
            out_file.print("jsmntok_t token_buffer[token_num];")
            out_file.print("memset(token_buffer, 0, sizeof token_buffer);")
            with out_file.if_block("builtin_parse_json_string(parse_state, token_buffer, (size_t) token_num, json_string, json_string_len) < 0"):
                out_file.print("return true;")
            self.root_generator.generate_parser_call(
                "out",
                out_file,
            )
            out_file.print("return false;")
        out_file.print("/*@=temptrans@*/")
        out_file.print("")

        out_file.print("bool json_parse_{}(const char *json_string, {})".format(self.name, self.root_generator.c_type.typed_identifier("out", indirection="*")))
        with out_file.code_block():
            out_file.print("return json_parse_{}_with_len(json_string, strlen(json_string), out);".format(self.name))
        out_file.print("")

        out_file.print("bool file_parse_{}(const char *filepath, {})".format(self.name, self.root_generator.c_type.typed_identifier("out", indirection="*")))
        with out_file.code_block():
            exit_err = lambda msg: out_file.print(['LOG_ERROR(-1, {})'.format(msg), "(void) close(fd);", "return true;"])

            out_file.print("int fd = open(filepath, O_RDONLY);")
            with out_file.if_block("fd < 0"):
                exit_err('"cannot open JSON file \\"%s\\": %s", filepath, strerror(errno)')
            out_file.print("")

            out_file.print("const off_t file_size_or_err = lseek(fd, 0, SEEK_END);")
            with out_file.if_block("file_size_or_err < 0"):
                exit_err('"cannot seek JSON file \\"%s\\": %s", filepath, strerror(errno)')
            out_file.print("const size_t file_size = (size_t) file_size_or_err;")
            out_file.print("")

            if self.settings.file_parser_max_size is not None:
                with out_file.if_block("file_size > (size_t) ({})".format(self.settings.file_parser_max_size)):
                    exit_err('"JSON file \\"%s\\" size is greater than max allowed size (%zu bytes), got %jd", filepath, (size_t) ({}), (intmax_t) file_size'.format(self.settings.file_parser_max_size))
                out_file.print("")

            out_file.print("void *const file_content = mmap(NULL, file_size, PROT_READ, MAP_PRIVATE, fd, 0);")
            with out_file.if_block("file_content == MAP_FAILED"):
                exit_err('"cannot memory map JSON file \\"%s\\": %s", filepath, strerror(errno)')
            out_file.print("")

            out_file.print("bool res = json_parse_{}_with_len(file_content, file_size, out);".format(self.name))
            out_file.print("")

            out_file.print("(void) munmap(file_content, file_size);")
            out_file.print("(void) close(fd);")
            out_file.print("return res;")
        out_file.print("")


    def generate_parser_h(self, h_file_path: str):
        h_file = CodeBlockPrinter(h_file_path)

        h_file.write(NOTE_FOR_GENERATED_FILES)

        header_guard_name = re.sub("[^A-Z0-9]", "_", os.path.basename(h_file_path).upper())
        h_file.print("#ifndef {}".format(header_guard_name))
        h_file.print("#define {}".format(header_guard_name))

        h_file.print("#include <stdbool.h>")
        h_file.print("#include <stddef.h>")
        h_file.print("#include <stdint.h>")

        if self.settings.h_prefix_file is not None:
            h_file.print_separator("User-added prefix")
            h_file.write(self.settings.h_prefix_file.read())

        h_file.print("#ifdef __cplusplus")
        h_file.print("extern \"C\" {")
        h_file.print("#endif")

        h_file.print_separator("Generated type declarations")
        self.root_generator.c_type.generate_type_declaration(h_file)
        h_file.print("bool json_parse_{}(const char *json_string, {});".format(self.name, self.root_generator.c_type.typed_identifier("out", indirection="*")))
        h_file.print("bool json_parse_{}_with_len(const char *json_string, size_t json_string_len, {});".format(self.name, self.root_generator.c_type.typed_identifier("out", indirection="*")))
        h_file.print("bool file_parse_{}(const char *filepath, {});".format(self.name, self.root_generator.c_type.typed_identifier("out", indirection="*")))

        h_file.print("#ifdef __cplusplus")
        h_file.print("}")
        h_file.print("#endif")

        if self.settings.h_postfix_file:
            h_file.print_separator("User-added postfix")
            h_file.write(self.settings.h_postfix_file.read())

        h_file.print("#endif /* {} */".format(header_guard_name))
        h_file.print("")

        h_file.save_to_file()

    @classmethod
    def manually_include_jsmn(cls, c_file: CodeBlockPrinter):
        with open(os.path.join(DIR_OF_THIS_FILE, 'jsmn.h'), encoding='utf-8') as jsmn_h:
            c_file.print("")
            c_file.print_separator("jsmn.h (From https://github.com/zserge/jsmn)")
            c_file.write(jsmn_h.read())
            c_file.print_separator("end of jsmn.h")
            c_file.print("")

    @classmethod
    def manually_include_builtins(cls, c_file: CodeBlockPrinter):
        with open(os.path.join(DIR_OF_THIS_FILE, 'js2c_builtins.h'), encoding='utf-8') as builtins_file:
            c_file.print_separator("js2c_builtins.h")
            builtins_file_contents = builtins_file.read()
            jsmn_include_string = '#include "jsmn.h"\n'
            split_pos = builtins_file_contents.index(jsmn_include_string)
            if split_pos < 0:
                raise ValueError("{} not found in builtins file".format(jsmn_include_string))
            c_file.write(builtins_file_contents[:split_pos])
            cls.manually_include_jsmn(c_file)
            c_file.write(builtins_file_contents[split_pos + len(jsmn_include_string):])

            c_file.print_separator("end of js2c_builtins.h")
            c_file.print("")

    def generate_parser_c(self, c_file_path: str, h_file_name: str):
        c_file = CodeBlockPrinter(c_file_path)

        c_file.write(NOTE_FOR_GENERATED_FILES)
        c_file.print('#include "{}"'.format(h_file_name))
        c_file.print("/*@+matchanyintegral@*/ // FIXME fix this mess")

        if self.settings.c_prefix_file is not None:
            c_file.print_separator("User-added prefix")
            c_file.write(self.settings.c_prefix_file.read())

        if self.settings.include_external_builtins_file:
            c_file.print('#include "{}"'.format(self.settings.include_external_builtins_file))
        else:
            self.manually_include_builtins(c_file)
        c_file.print_separator("Generated parsers")
        c_file.print("")
        self.root_generator.generate_parser_bodies(c_file)
        self.generate_root_parser(c_file)

        if self.settings.c_postfix_file:
            c_file.print_separator("User-added postfix")
            c_file.write(self.settings.c_postfix_file.read())

        c_file.print("/*@=matchanyintegral@*/")
        c_file.print("")

        c_file.save_to_file()
